<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="TR-JDGMXY2" failures="2" tests="2" name="HeaderSectionTest" time="3.108" errors="0" timestamp="2021-02-26T02:26:43 ART">
  <testcase classname="com.trgr.quality.maf.tests.HeaderSectionTest" name="headerSectionLinks" time="0.017">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Exception in Test expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Exception in Test expected [true] but found [false]
at com.trgr.quality.maf.tests.HeaderSectionTest.headerSectionLinks(HeaderSectionTest.java:93)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- headerSectionLinks -->
  <testcase classname="com.trgr.quality.maf.tests.HeaderSectionTest" name="loggedinUserDetails" time="3.012">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Exception in Test expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Exception in Test expected [true] but found [false]
at com.trgr.quality.maf.tests.HeaderSectionTest.loggedinUserDetails(HeaderSectionTest.java:127)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- loggedinUserDetails -->
  <testcase classname="com.trgr.quality.maf.tests.HeaderSectionTest" name="headerSectionUniqueUrls" time="0.0">
    <ignored/>
  </testcase> <!-- headerSectionUniqueUrls -->
  <testcase classname="com.trgr.quality.maf.tests.HeaderSectionTest" name="goToLegalArea" time="0.0">
    <ignored/>
  </testcase> <!-- goToLegalArea -->
  <testcase classname="com.trgr.quality.maf.tests.HeaderSectionTest" name="goToCheckpointUSA" time="0.0">
    <ignored/>
  </testcase> <!-- goToCheckpointUSA -->
  <testcase classname="com.trgr.quality.maf.tests.HeaderSectionTest" name="FAQ" time="0.0">
    <ignored/>
  </testcase> <!-- FAQ -->
  <testcase classname="com.trgr.quality.maf.tests.HeaderSectionTest" name="goToCheckpointWorld" time="0.0">
    <ignored/>
  </testcase> <!-- goToCheckpointWorld -->
</testsuite> <!-- HeaderSectionTest -->
