<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="TR-JDGMXY2" failures="1" tests="1" name="HelpTest" time="0.074" errors="0" timestamp="2021-02-26T02:42:53 ART">
  <testcase classname="com.trgr.quality.maf.tests.HelpTest" name="HelpLinkPresenceforAll" time="0.015">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Exception in Test expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Exception in Test expected [true] but found [false]
at com.trgr.quality.maf.tests.HelpTest.HelpLinkPresenceforAll(HelpTest.java:158)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- HelpLinkPresenceforAll -->
  <testcase classname="com.trgr.quality.maf.tests.HelpTest" name="RedirectedHelpLinkValidation" time="0.0">
    <ignored/>
  </testcase> <!-- RedirectedHelpLinkValidation -->
  <testcase classname="com.trgr.quality.maf.tests.HelpTest" name="HelpLinkPresence" time="0.0">
    <ignored/>
  </testcase> <!-- HelpLinkPresence -->
</testsuite> <!-- HelpTest -->
