<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="TR-JDGMXY2" failures="1" tests="1" name="LinkUtilityTest" time="0.184" errors="0" timestamp="2021-02-26T02:42:53 ART">
  <testcase classname="com.trgr.quality.maf.tests.LinkUtilityTest" name="valdiateLinksPresent" time="0.028">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Exception in Test expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Exception in Test expected [true] but found [false]
at com.trgr.quality.maf.tests.LinkUtilityTest.valdiateLinksPresent(LinkUtilityTest.java:103)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- valdiateLinksPresent -->
</testsuite> <!-- LinkUtilityTest -->
