<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="TR-JDGMXY2" failures="2" tests="2" name="SignoffTest" time="0.092" errors="0" timestamp="2021-02-26T02:42:54 ART">
  <testcase classname="com.trgr.quality.maf.tests.ToolsTest" name="@BeforeClass startToolsTest" time="0.024">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.trgr.quality.maf.tests.ToolsTest.startToolsTest(ToolsTest.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass startToolsTest -->
  <testcase classname="com.trgr.quality.maf.tests.SignoffTest" name="Signoff" time="0.01">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Exception in Test expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Exception in Test expected [true] but found [false]
at com.trgr.quality.maf.tests.SignoffTest.Signoff(SignoffTest.java:104)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Signoff -->
  <testcase classname="com.trgr.quality.maf.tests.SignoffTest" name="NavigationfromSignofftologinPage" time="0.029">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Exception in Test expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Exception in Test expected [true] but found [false]
at com.trgr.quality.maf.tests.SignoffTest.NavigationfromSignofftologinPage(SignoffTest.java:187)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- NavigationfromSignofftologinPage -->
  <testcase classname="com.trgr.quality.maf.tests.SignoffTest" name="displayOfSignOffSummary" time="0.0">
    <ignored/>
  </testcase> <!-- displayOfSignOffSummary -->
</testsuite> <!-- SignoffTest -->
